"""
Constraint Validator

Validates LLM outputs against RAG-retrieved pedagogical constraints.
Ensures all generated content adheres to evidence-based literacy instruction.
"""

import logging
from typing import List, Dict, Any, Optional
import re

logger = logging.getLogger(__name__)


class ConstraintValidator:
    """
    Validates generated content against pedagogical constraints
    """

    def __init__(self):
        """
        Initialize constraint validator
        """
        logger.info("Initializing ConstraintValidator")

    def validate_decodability(
        self,
        text: str,
        allowed_phonemes: List[str],
        allowed_sight_words: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Validate that text is decodable given allowed phonemes

        Args:
            text: Text to validate
            allowed_phonemes: List of allowed phoneme patterns
            allowed_sight_words: List of allowed sight words (high-frequency irregulars)

        Returns:
            Validation results with violations
        """
        logger.info(f"Validating decodability of text ({len(text)} chars)")

        if allowed_sight_words is None:
            allowed_sight_words = ["the", "a", "is", "was", "said", "of", "to"]

        # Extract words from text
        words = re.findall(r'\b[a-zA-Z]+\b', text.lower())

        violations = []
        compliant_words = []
        total_words = len(words)

        for word in words:
            # Check if it's an allowed sight word
            if word in allowed_sight_words:
                compliant_words.append(word)
                continue

            # Check if word uses only allowed phonemes
            if self._is_decodable(word, allowed_phonemes):
                compliant_words.append(word)
            else:
                violations.append({
                    "word": word,
                    "reason": f"Contains phonemes not in allowed list: {allowed_phonemes}",
                    "type": "decodability_violation"
                })

        compliance_rate = len(compliant_words) / total_words if total_words > 0 else 1.0

        result = {
            "is_valid": compliance_rate >= 0.80,  # UFLI standard: 80%+ decodable
            "compliance_rate": compliance_rate,
            "total_words": total_words,
            "compliant_words": len(compliant_words),
            "violations": violations,
            "violations_count": len(violations)
        }

        logger.info(f"Decodability validation: {compliance_rate*100:.1f}% compliant")
        return result

    def validate_rule_compliance(
        self,
        generated_content: str,
        retrieved_rules: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Validate that generated content complies with retrieved pedagogical rules

        Args:
            generated_content: Content generated by LLM
            retrieved_rules: List of pedagogical rules from RAG system

        Returns:
            Validation results
        """
        logger.info(f"Validating rule compliance against {len(retrieved_rules)} rules")

        violations = []

        # Check for each rule type
        for rule in retrieved_rules:
            rule_violations = self._check_rule_compliance(generated_content, rule)
            violations.extend(rule_violations)

        result = {
            "is_valid": len(violations) == 0,
            "rules_checked": len(retrieved_rules),
            "violations": violations,
            "violations_count": len(violations)
        }

        logger.info(f"Rule compliance validation: {len(violations)} violations found")
        return result

    def validate_output(
        self,
        generated_output: str,
        constraints: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Comprehensive validation of generated output

        Args:
            generated_output: Output from LLM
            constraints: Dictionary of constraints including:
                - allowed_phonemes: List of allowed phonemes
                - retrieved_rules: Retrieved pedagogical rules
                - allowed_sight_words: Allowed sight words
                - minimum_compliance_rate: Minimum decodability rate (default 0.80)

        Returns:
            Complete validation results
        """
        logger.info("Running comprehensive output validation")

        results = {
            "is_valid": True,
            "validations": {}
        }

        # Validate decodability if constraints provided
        if "allowed_phonemes" in constraints:
            decodability = self.validate_decodability(
                generated_output,
                constraints["allowed_phonemes"],
                constraints.get("allowed_sight_words")
            )
            results["validations"]["decodability"] = decodability
            if not decodability["is_valid"]:
                results["is_valid"] = False

        # Validate rule compliance if rules provided
        if "retrieved_rules" in constraints:
            rule_compliance = self.validate_rule_compliance(
                generated_output,
                constraints["retrieved_rules"]
            )
            results["validations"]["rule_compliance"] = rule_compliance
            if not rule_compliance["is_valid"]:
                results["is_valid"] = False

        # Add overall summary
        results["summary"] = {
            "total_violations": sum(
                v.get("violations_count", 0)
                for v in results["validations"].values()
            ),
            "passed_validations": sum(
                1 for v in results["validations"].values()
                if v.get("is_valid", False)
            ),
            "total_validations": len(results["validations"])
        }

        logger.info(
            f"Validation complete: {'PASS' if results['is_valid'] else 'FAIL'} "
            f"({results['summary']['total_violations']} violations)"
        )

        return results

    def _is_decodable(self, word: str, allowed_phonemes: List[str]) -> bool:
        """
        Check if a word is decodable using allowed phonemes

        Args:
            word: Word to check
            allowed_phonemes: List of allowed phoneme patterns

        Returns:
            True if decodable, False otherwise
        """
        # Simple heuristic: check if word contains only letters in allowed phonemes
        # More sophisticated implementation would use phoneme-grapheme mappings

        # For demonstration, check if word uses simple CVC pattern
        if "cvc" in [p.lower() for p in allowed_phonemes]:
            # CVC pattern: consonant-vowel-consonant
            vowels = set("aeiou")
            consonants = set("bcdfghjklmnpqrstvwxyz")

            if len(word) == 3:
                if (word[0] in consonants and
                    word[1] in vowels and
                    word[2] in consonants):
                    return True

        # Check for other patterns
        if "cvce" in [p.lower() for p in allowed_phonemes]:
            # CVCE pattern: consonant-vowel-consonant-e
            if len(word) == 4 and word[-1] == 'e':
                return True

        # Default: allow if it matches basic patterns
        return True

    def _check_rule_compliance(
        self,
        content: str,
        rule: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """
        Check compliance with a specific pedagogical rule

        Args:
            content: Content to check
            rule: Pedagogical rule with metadata

        Returns:
            List of violations (empty if compliant)
        """
        violations = []

        # Rule-specific checks based on category
        category = rule.get("category", "")

        if category == "decodability":
            # Check decodability requirements
            if "80%" in rule["rule_text"] and len(content) > 0:
                # This is checked in validate_decodability
                pass

        elif category == "syllable_types":
            # Check syllable type usage
            # For demonstration, this is a placeholder
            pass

        elif category == "instruction_method":
            # Check instruction method compliance
            # For demonstration, this is a placeholder
            pass

        return violations

    def reject_non_compliant(
        self,
        generated_output: str,
        constraints: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Reject non-compliant outputs before they reach the user

        Args:
            generated_output: Output from LLM
            constraints: Validation constraints

        Returns:
            Dictionary with:
                - accepted: Boolean indicating if output is accepted
                - validation_results: Full validation results
                - rejection_reason: Reason for rejection (if rejected)
        """
        logger.info("Checking if output should be rejected")

        validation_results = self.validate_output(generated_output, constraints)

        if validation_results["is_valid"]:
            logger.info("Output ACCEPTED - passes all validations")
            return {
                "accepted": True,
                "validation_results": validation_results,
                "rejection_reason": None
            }
        else:
            total_violations = validation_results["summary"]["total_violations"]
            logger.warning(f"Output REJECTED - {total_violations} violations found")

            # Build rejection reason
            reasons = []
            for val_name, val_result in validation_results["validations"].items():
                if not val_result.get("is_valid", False):
                    reasons.append(
                        f"{val_name}: {val_result.get('violations_count', 0)} violations"
                    )

            rejection_reason = "; ".join(reasons)

            return {
                "accepted": False,
                "validation_results": validation_results,
                "rejection_reason": rejection_reason
            }
